eureka:
  instance:
    prefer-ip-address: true
  client:
#If fetch registry is not given here, it is true by default
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
