eureka:
  instance:
    prefer-ip-address: true
  client:
#If fetch registry is not given here, it is true by default
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Zipkin Configuration    
# All the request are sampled( 1.0=100 percent)     
management:
  tracing:
    sampling:
      probability: 1.0   
  zipkin:
    tracing:
      endpoint: http://localhost:9411/
      
