eureka:
  instance:
    prefer-ip-address: true
  client:
#If fetch registry is not given here, it is true by default
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

#Logging Traces and Spans in the following format:
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"


# Zipkin Configuration    
# All the request are sampled( 1.0=100 percent)     
management:
  tracing:
    sampling:
      probability: 1.0   
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      
      
